### ISSUE TITLE
Build error: Access to path "bin\NetCoreApp3_win_x64\bin" is denied.

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/azure-functions-extension-bundles#79]
I encountered build error in PR #78 .  The first commit passed the build while the second commit failed.  I try to build the project locally (see the steps and logs attached), but neither commit succeeded. Also there is no dependency change between the two commits.  So I believe there are some environmental changes between these two commits. 

Under `build/` directory, run ```dotnet run  skip:GenerateNetCoreV3BundlesLinux,CreateCDNStoragePackageLinux,BuildBundleBinariesForLinux  /p:PublishReadyToRunShowWarnings=true ```

Here are the logs:
[log1.4.1.txt](https://github.com/Azure/azure-functions-extension-bundles/files/6582032/log1.4.1.txt)

The error is 
```
Unhandled exception. System.IO.IOException: Access to the path 'C:\Users\xxx\source\repos\azure-functions-extension-bundles\bin\NetCoreApp3_win_x64\bin' is denied.
  at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
  at System.IO.Directory.Move(String sourceDirName, String destDirName)
  at Build.BuildSteps.BuildExtensionsBundle(BuildConfiguration buildConfig) in C:\Users\xxx\source\repos\azure-functions-extension-bundles\build\BuildSteps.cs:line 121
  at Build.BuildSteps.<>c.<BuildBundleBinariesForWindows>b__2_0(BuildConfiguration config) in C:\Users\xxx\source\repos\azure-functions-extension-bundles\build\BuildSteps.cs:line 65
  at System.Collections.Generic.List`1.ForEach(Action`1 action)
  at Build.BuildSteps.BuildBundleBinariesForWindows() in C:\Users\xxx\source\repos\azure-functions-extension-bundles\build\BuildSteps.cs:line 65
  at Build.Orchestrator.Run() in C:\Users\xxx\source\repos\azure-functions-extension-bundles\build\Orchestrator.cs:line 69
  at Build.Program.Main(String[] args) in C:\Users\xxx\source\repos\azure-functions-extension-bundles\build\Program.cs:line 12
```

**Comment by Y-Sindo** [comment]
I updated again and this time the build was successful.
